// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Reddit_API.Migrations
{
    [DbContext(typeof(TrådContext))]
    partial class TrådContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Model.Kommentar", b =>
                {
                    b.Property<long>("KommentarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("KForfatter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Stemmer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TrådID")
                        .HasColumnType("INTEGER");

                    b.HasKey("KommentarID");

                    b.HasIndex("TrådID");

                    b.ToTable("Kommentar");
                });

            modelBuilder.Entity("Model.Tråd", b =>
                {
                    b.Property<long>("TrådID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Dato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Indhold")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Overskrift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Stemmer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TForfatter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TrådID");

                    b.ToTable("Tråde");
                });

            modelBuilder.Entity("Model.Kommentar", b =>
                {
                    b.HasOne("Model.Tråd", null)
                        .WithMany("KommentarListe")
                        .HasForeignKey("TrådID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Tråd", b =>
                {
                    b.Navigation("KommentarListe");
                });
#pragma warning restore 612, 618
        }
    }
}
